### ISSUE TITLE
Issue signing with Ledger

### ISSUE THREAD

**Issue by craig59** [unchained-capital/caravan#22] opened 2020-01-18 05:32 UTC
I have successfully created a redeem script for a 2 of 2 wallet for the bitcoin testnet, P2SH using a Trezor and Ledger. 

BIP32 Paths:
  * Public Key 1: m/45'/1'/0'/0
  * Public Key 2: m/45'/1'/0'/0

I can also confirm ownership using both the Trezor and Ledger.

However, when it comes to actually signing a transaction, after trying to confirm the fee and send on the Ledger, it freezes for about 10 secs, then Caravan gives the following error: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE. Signing with the Trezor works fine.

On the Ledger I get a message "The derivation path is unusual!" before importing the public key or signing.

I have tried on a Mac and Windows PC to no avail.

**Comment by bucko13** [comment] 2020-03-24 19:48
Hi @craig59,
Sorry for the delay in responding to this. Signing with ledger should work. Unfortunately, there's no way to get around the message you're seeing though. Ledger's UX isn't really optimized for custom multisig setups and so the message about the derivation path being unusual is to be expected and can be safely ignored. The reason it says that is that it notices the path isn't the normal BIP44 path for normal P2PKH addresses that it's been told to expect. 

The library we use in Caravan for wallet interactions [unchained-wallets](https://github.com/unchained-capital/unchained-wallets) has added support for images to correspond with specific interactions, including the unusual message! So hopefully that helps similar confusion in the future once Caravan has been upgraded (coming soon!)

If you click past that then the ledger should be able to sign just fine. If it's still not working, could you share the version of ledger (firmware and hardware) that you're using as well as the version of caravan?

**Comment by bucko13** [comment] 2020-05-19 13:47
Closing as this is expected behavior. Clicking through the warning message from ledger should get you to the signing step. Feel free to re-open or open a new issue if you're still having trouble.

**Closed by bucko13** 2020-05-19 13:47 UTC
Labels: help wanted
